/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 public/models/pencil2.glb
*/

import React, { useRef,useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('./models/pencil2.glb')
  const { actions,names } = useAnimations(animations, group)
  
  useEffect(()=>{
    actions[names[0]].reset().fadeIn(0.5).play()
  },[])
  
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="t00" position={[-0.049, 0.012, 0.01]} />
        <group name="t005" position={[1.387, 0.012, 0.01]} />
        <group name="t00100" position={[1.387, 0.012, 0.01]} />
        <group name="t00200" position={[2.431, 0.012, 0.01]} />
        <group name="t006" position={[3.866, 0.012, 0.01]} />
        <group name="t00300" position={[3.866, 0.012, 0.01]} />
        <group name="t007" position={[4.988, 0.012, 0.01]} />
        <group name="t00400" position={[4.988, 0.012, 0.01]} />
        <group name="WritingAnim_Guide" position={[1.167, 0.012, -1.19]}>
          <group name="pencil" position={[0, 1.288, 0]} scale={[0.211, 0.861, 0.211]}>
            <mesh name="Cylinder" geometry={nodes.Cylinder.geometry} material={materials.Pencil} />
            <mesh name="Cylinder_1" geometry={nodes.Cylinder_1.geometry} material={materials.Middle} />
            <mesh name="Cylinder_2" geometry={nodes.Cylinder_2.geometry} material={materials.Wood} />
            <mesh name="Cylinder_3" geometry={nodes.Cylinder_3.geometry} material={materials.grif} />
            <mesh name="Cylinder_4" geometry={nodes.Cylinder_4.geometry} material={materials.Metal} />
            <mesh name="Cylinder_5" geometry={nodes.Cylinder_5.geometry} material={materials.eraser} />
          </group>
        </group>
        <mesh name="paper" geometry={nodes.paper.geometry} material={materials.Paper} position={[3.292, 0, 1.846]} scale={[1.184, 1, 0.701]} />
        <mesh name="Cube" geometry={nodes.Cube.geometry} material={materials['Material.001']} position={[2.419, -1.114, -0.498]} rotation={[0, 0, -Math.PI]} scale={[-4.772, -1, -2.739]} />
      </group>
    </group>
  )
}

useGLTF.preload('./models/pencil2.glb')
