/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 public/models/room.glb
*/

import React, { useRef, useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('./models/room.glb')
  const { actions, names } = useAnimations(animations, group)

  useEffect(()=>{
    actions[names[0]].reset().fadeIn(0.5).play()
  },[])

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh name="Plane" geometry={nodes.Plane.geometry} material={materials['Material.006']} scale={[5.633, 5.633, 6.414]} />
        <mesh name="Cube001" geometry={nodes.Cube001.geometry} material={materials.raft} position={[-1.991, 1.056, 1.782]} scale={[3.647, 1, 1.39]} />
        <mesh name="Cube002" geometry={nodes.Cube002.geometry} material={materials.raft} position={[0.66, 3.068, 1.782]} scale={[1, 1, 1.39]} />
        <mesh name="Cube003" geometry={nodes.Cube003.geometry} material={materials.raft} position={[-1.345, 3.068, 1.782]} scale={[1, 1, 1.39]} />
        <mesh name="Cylinder" geometry={nodes.Cylinder.geometry} material={materials.teava} position={[-3.583, 0.451, -1.631]} scale={[1.25, 0.446, 1.25]} />
        <mesh name="Cube004" geometry={nodes.Cube004.geometry} material={materials['Material.010']} position={[1.488, 4.252, 4.763]} scale={[3.906, 4.246, 1.575]} />
        <mesh name="Cube005" geometry={nodes.Cube005.geometry} material={materials['Material.001']} position={[3.507, 1.573, 1.767]} scale={[1.828, 1.539, 1.41]} />
        <mesh name="Cube006" geometry={nodes.Cube006.geometry} material={materials['Material.005']} position={[3.507, 4.213, 1.767]} scale={[1.828, 1.08, 1.41]} />
        <mesh name="Cube007" geometry={nodes.Cube007.geometry} material={materials['Material.004']} position={[3.507, 1.573, -1.114]} scale={[1.828, 1.539, 1.451]} />
        <mesh name="Plane001" geometry={nodes.Plane001.geometry} material={materials.comp} position={[-3.995, 3.375, 2.82]} rotation={[Math.PI / 2, 0, 0]} scale={1.198} />
        <mesh name="Plane002" geometry={nodes.Plane002.geometry} material={materials['Material.008']} position={[-3.98, 3.357, 2.658]} rotation={[Math.PI / 2, 0, 0]} scale={[1.033, 0.155, 1.033]} />
        <mesh name="Plane003" geometry={nodes.Plane003.geometry} material={materials.comp} position={[-1.15, 7.183, 3.084]} rotation={[Math.PI / 2, 0, 0]} scale={[0.439, 0.083, 0.577]} />
        <mesh name="Plane004" geometry={nodes.Plane004.geometry} material={materials.comp} position={[0.653, 5.576, 3.125]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={[0.83, 0.168, 0.83]} />
        <mesh name="Plane005" geometry={nodes.Plane005.geometry} material={materials['vazoncik mov']} position={[-1.117, 7.054, 3.125]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={[0.791, 0.16, 0.791]} />
        <mesh name="Cylinder001" geometry={nodes.Cylinder001.geometry} material={materials.comp} position={[-2.759, 6.896, 4.769]} rotation={[0, 0, -Math.PI / 2]} scale={[1.242, 0.293, 1.242]} />
        <mesh name="Cube019" geometry={nodes.Cube019.geometry} material={materials.Material} position={[-2.933, 6.207, 5.216]} rotation={[-Math.PI / 6, 0, Math.PI]} scale={[0.033, 0.184, 0.039]} />
        <mesh name="Cylinder002" geometry={nodes.Cylinder002.geometry} material={materials.Material} position={[-2.919, 6.895, 4.814]} rotation={[0, 0, -Math.PI / 2]} scale={0.076} />
        <mesh name="Cube008" geometry={nodes.Cube008.geometry} material={materials.Material} position={[-2.995, 6.93, 4.83]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.033, -0.394, -0.033]} />
        <mesh name="Cube009" geometry={nodes.Cube009.geometry} material={materials.Material} position={[-2.9, 7.169, 4.748]} rotation={[2.901, -0.017, -3.112]} scale={[-0.033, -0.278, -0.033]} />
        <mesh name="Cube010" geometry={nodes.Cube010.geometry} material={materials['carte mov']} position={[4.595, 5.392, 2.681]} scale={[0.308, 0.09, 0.308]} />
        <mesh name="Cube011" geometry={nodes.Cube011.geometry} material={materials['carte albastru']} position={[4.595, 5.576, 2.681]} scale={[0.308, 0.09, 0.308]} />
        <mesh name="Cube012" geometry={nodes.Cube012.geometry} material={materials['carte marine']} position={[4.595, 5.761, 2.681]} scale={[0.308, 0.09, 0.308]} />
        <mesh name="Cube013" geometry={nodes.Cube013.geometry} material={materials['carte mov']} position={[4.595, 5.947, 2.681]} scale={[0.308, 0.09, 0.308]} />
        <mesh name="Cube014" geometry={nodes.Cube014.geometry} material={materials['carte albastru']} position={[4.595, 6.132, 2.681]} scale={[0.308, 0.09, 0.308]} />
        <mesh name="Cube015" geometry={nodes.Cube015.geometry} material={materials['carte mov']} position={[4.595, 6.321, 2.681]} scale={[0.308, 0.09, 0.308]} />
        <mesh name="Cube016" geometry={nodes.Cube016.geometry} material={materials['carte marine']} position={[4.595, 6.507, 2.681]} scale={[0.308, 0.09, 0.308]} />
        <mesh name="Cube017" geometry={nodes.Cube017.geometry} material={materials['carte albastru']} position={[4.595, 6.692, 2.681]} scale={[0.308, 0.09, 0.308]} />
        <mesh name="Cube018" geometry={nodes.Cube018.geometry} material={nodes.Cube018.material} position={[3.93, 5.4, 2.703]} scale={[0.308, 0.09, 0.308]} />
        <mesh name="Cube020" geometry={nodes.Cube020.geometry} material={nodes.Cube020.material} position={[3.93, 5.586, 2.703]} scale={[0.308, 0.09, 0.308]} />
        <mesh name="Cube021" geometry={nodes.Cube021.geometry} material={nodes.Cube021.material} position={[3.93, 5.771, 2.703]} scale={[0.308, 0.09, 0.308]} />
        <mesh name="Cube022" geometry={nodes.Cube022.geometry} material={materials['carte marine']} position={[3.93, 5.96, 2.703]} scale={[0.308, 0.09, 0.308]} />
        <mesh name="Cube023" geometry={nodes.Cube023.geometry} material={materials['carte albastru']} position={[3.93, 6.145, 2.703]} scale={[0.308, 0.09, 0.308]} />
        <mesh name="Cube024" geometry={nodes.Cube024.geometry} material={materials['carte mov']} position={[3.93, 6.33, 2.703]} scale={[0.308, 0.09, 0.308]} />
        <mesh name="Cube025" geometry={nodes.Cube025.geometry} material={materials['carte marine']} position={[3.93, 6.514, 2.703]} scale={[0.308, 0.09, 0.308]} />
        <mesh name="Cube026" geometry={nodes.Cube026.geometry} material={nodes.Cube026.material} position={[3.252, 5.4, 2.703]} scale={[0.308, 0.09, 0.308]} />
        <mesh name="Cube027" geometry={nodes.Cube027.geometry} material={materials['carte marine']} position={[3.252, 5.586, 2.703]} scale={[0.308, 0.09, 0.308]} />
        <mesh name="Cube028" geometry={nodes.Cube028.geometry} material={materials['carte marine']} position={[3.252, 5.771, 2.703]} scale={[0.308, 0.09, 0.308]} />
        <mesh name="Cube029" geometry={nodes.Cube029.geometry} material={materials['carte mov']} position={[3.252, 5.96, 2.703]} scale={[0.308, 0.09, 0.308]} />
        <mesh name="Cube030" geometry={nodes.Cube030.geometry} material={materials['carte marine']} position={[3.252, 6.145, 2.703]} scale={[0.308, 0.09, 0.308]} />
        <mesh name="Cube031" geometry={nodes.Cube031.geometry} material={materials['carte albastru']} position={[3.252, 6.33, 2.703]} scale={[0.308, 0.09, 0.308]} />
        <mesh name="Cube032" geometry={nodes.Cube032.geometry} material={materials['carte albastru']} position={[2.574, 5.4, 2.703]} scale={[0.308, 0.09, 0.308]} />
        <mesh name="Cube033" geometry={nodes.Cube033.geometry} material={materials['carte marine']} position={[2.574, 5.586, 2.703]} scale={[0.308, 0.09, 0.308]} />
        <mesh name="Cube034" geometry={nodes.Cube034.geometry} material={materials['carte albastru']} position={[2.574, 5.771, 2.703]} scale={[0.308, 0.09, 0.308]} />
        <mesh name="Cube035" geometry={nodes.Cube035.geometry} material={materials['carte mov']} position={[2.574, 5.96, 2.703]} scale={[0.308, 0.09, 0.308]} />
        <mesh name="Cube036" geometry={nodes.Cube036.geometry} material={materials['carte marine']} position={[2.574, 6.145, 2.703]} scale={[0.308, 0.09, 0.308]} />
        <mesh name="Cube037" geometry={nodes.Cube037.geometry} material={materials['carte albastru']} position={[4.595, 5.392, 1.988]} scale={[0.308, 0.09, 0.308]} />
        <mesh name="Cube038" geometry={nodes.Cube038.geometry} material={materials['carte marine']} position={[4.595, 5.576, 1.988]} scale={[0.308, 0.09, 0.308]} />
        <mesh name="Cube039" geometry={nodes.Cube039.geometry} material={materials['carte albastru']} position={[4.595, 5.761, 1.988]} scale={[0.308, 0.09, 0.308]} />
        <mesh name="Cube040" geometry={nodes.Cube040.geometry} material={materials['carte marine']} position={[4.595, 5.947, 1.988]} scale={[0.308, 0.09, 0.308]} />
        <mesh name="Cube041" geometry={nodes.Cube041.geometry} material={materials['carte mov']} position={[4.595, 6.132, 1.988]} scale={[0.308, 0.09, 0.308]} />
        <mesh name="Cube042" geometry={nodes.Cube042.geometry} material={materials['carte albastru']} position={[4.595, 6.321, 1.988]} scale={[0.308, 0.09, 0.308]} />
        <mesh name="Cube043" geometry={nodes.Cube043.geometry} material={materials['carte marine']} position={[4.595, 6.507, 1.988]} scale={[0.308, 0.09, 0.308]} />
        <mesh name="Cube045" geometry={nodes.Cube045.geometry} material={nodes.Cube045.material} position={[3.934, 5.392, 1.988]} scale={[0.308, 0.09, 0.308]} />
        <mesh name="Cube046" geometry={nodes.Cube046.geometry} material={nodes.Cube046.material} position={[3.934, 5.576, 1.988]} scale={[0.308, 0.09, 0.308]} />
        <mesh name="Cube049" geometry={nodes.Cube049.geometry} material={materials['carte marine']} position={[3.934, 6.132, 1.988]} scale={[0.308, 0.09, 0.308]} />
        <mesh name="Cube053" geometry={nodes.Cube053.geometry} material={nodes.Cube053.material} position={[3.934, 5.392, 1.988]} scale={[0.308, 0.09, 0.308]} />
        <mesh name="Cube054" geometry={nodes.Cube054.geometry} material={nodes.Cube054.material} position={[3.934, 5.576, 1.988]} scale={[0.308, 0.09, 0.308]} />
        <mesh name="Cube061" geometry={nodes.Cube061.geometry} material={nodes.Cube061.material} position={[3.241, 5.392, 1.988]} scale={[0.308, 0.09, 0.308]} />
        <mesh name="Cube062" geometry={nodes.Cube062.geometry} material={materials['carte marine']} position={[3.241, 5.576, 1.988]} scale={[0.308, 0.09, 0.308]} />
        <mesh name="Cube063" geometry={nodes.Cube063.geometry} material={materials['carte mov']} position={[3.241, 5.761, 1.988]} scale={[0.308, 0.09, 0.308]} />
        <mesh name="Cube064" geometry={nodes.Cube064.geometry} material={materials['carte marine']} position={[3.241, 5.947, 1.988]} scale={[0.308, 0.09, 0.308]} />
        <mesh name="Cube065" geometry={nodes.Cube065.geometry} material={materials['carte albastru']} position={[3.241, 6.132, 1.988]} scale={[0.308, 0.09, 0.308]} />
        <mesh name="Cube069" geometry={nodes.Cube069.geometry} material={materials['carte mov']} position={[2.585, 5.392, 1.988]} scale={[0.308, 0.09, 0.308]} />
        <mesh name="Cube070" geometry={nodes.Cube070.geometry} material={materials['carte albastru']} position={[2.585, 5.576, 1.988]} scale={[0.308, 0.09, 0.308]} />
        <mesh name="Cube071" geometry={nodes.Cube071.geometry} material={materials['carte marine']} position={[2.585, 5.761, 1.988]} scale={[0.308, 0.09, 0.308]} />
        <mesh name="Cube072" geometry={nodes.Cube072.geometry} material={materials['carte mov']} position={[2.585, 5.947, 1.988]} scale={[0.308, 0.09, 0.308]} />
        <mesh name="Cube044" geometry={nodes.Cube044.geometry} material={materials['carte marine']} position={[4.595, 5.392, 1.287]} scale={[0.308, 0.09, 0.308]} />
        <mesh name="Cube051" geometry={nodes.Cube051.geometry} material={materials['carte albastru']} position={[4.595, 5.576, 1.287]} scale={[0.308, 0.09, 0.308]} />
        <mesh name="Cube052" geometry={nodes.Cube052.geometry} material={materials['carte marine']} position={[4.595, 5.761, 1.287]} scale={[0.308, 0.09, 0.308]} />
        <mesh name="Cube059" geometry={nodes.Cube059.geometry} material={materials['carte mov']} position={[4.595, 5.947, 1.287]} scale={[0.308, 0.09, 0.308]} />
        <mesh name="Cube060" geometry={nodes.Cube060.geometry} material={materials['carte albastru']} position={[4.595, 6.132, 1.287]} scale={[0.308, 0.09, 0.308]} />
        <mesh name="Cube068" geometry={nodes.Cube068.geometry} material={materials['carte albastru']} position={[3.934, 5.392, 1.287]} scale={[0.308, 0.09, 0.308]} />
        <mesh name="Cube073" geometry={nodes.Cube073.geometry} material={materials['carte mov']} position={[3.934, 5.576, 1.287]} scale={[0.308, 0.09, 0.308]} />
        <mesh name="Cube074" geometry={nodes.Cube074.geometry} material={materials['carte albastru']} position={[3.934, 5.761, 1.287]} scale={[0.308, 0.09, 0.308]} />
        <mesh name="Cube075" geometry={nodes.Cube075.geometry} material={materials['carte marine']} position={[3.934, 5.947, 1.287]} scale={[0.308, 0.09, 0.308]} />
        <mesh name="Cube078" geometry={nodes.Cube078.geometry} material={materials['carte marine']} position={[3.241, 5.392, 1.287]} scale={[0.308, 0.09, 0.308]} />
        <mesh name="Cube079" geometry={nodes.Cube079.geometry} material={materials['carte albastru']} position={[3.241, 5.576, 1.287]} scale={[0.308, 0.09, 0.308]} />
        <mesh name="Cube083" geometry={nodes.Cube083.geometry} material={materials['carte mov']} position={[2.585, 5.392, 1.287]} scale={[0.308, 0.09, 0.308]} />
        <mesh name="Cube084" geometry={nodes.Cube084.geometry} material={materials['carte marine']} position={[2.585, 5.576, 1.287]} scale={[0.308, 0.09, 0.308]} />
        <mesh name="Cube085" geometry={nodes.Cube085.geometry} material={materials['carte albastru']} position={[2.585, 5.761, 1.287]} scale={[0.308, 0.09, 0.308]} />
        <mesh name="Cylinder003" geometry={nodes.Cylinder003.geometry} material={materials['Material.009']} position={[-2.494, 3.057, 1.416]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[0.252, 0.033, 0.252]} />
        <mesh name="Plane006" geometry={nodes.Plane006.geometry} material={materials['carte mov']} position={[-2.425, 3.051, 1.676]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={0.558} />
        <mesh name="Cylinder004" geometry={nodes.Cylinder004.geometry} material={materials['Material.011']} position={[4.077, 1.949, -2.707]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.452, 0.058, 0.452]} />
        <mesh name="Plane007" geometry={nodes.Plane007.geometry} material={materials.comp} position={[3.611, 1.937, -2.583]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh name="Cube077" geometry={nodes.Cube077.geometry} material={materials['carte albastru']} position={[0.015, 2.893, 1.762]} rotation={[0, 0, -Math.PI / 2]} scale={[0.786, 1, 1]} />
        <mesh name="Cube080" geometry={nodes.Cube080.geometry} material={materials['carte rosie']} position={[0.395, 2.89, 1.757]} rotation={[0, 0, -Math.PI / 2]} scale={[0.786, 0.581, 1]} />
        <mesh name="Cube081" geometry={nodes.Cube081.geometry} material={materials['carte marine']} position={[0.712, 2.89, 1.757]} rotation={[0, 0, -Math.PI / 2]} scale={[0.786, 0.698, 1]} />
        <mesh name="Cube082" geometry={nodes.Cube082.geometry} material={materials['carte mov']} position={[1.17, 2.89, 1.757]} rotation={[0, 0, -1.364]} scale={[0.786, 0.581, 1]} />
        <mesh name="Cube087" geometry={nodes.Cube087.geometry} material={materials['carte albastru']} position={[0.204, 0.249, 1.802]} scale={[1.169, 1, 1]} />
        <mesh name="Cube088" geometry={nodes.Cube088.geometry} material={materials['carte marine']} position={[0.207, 0.629, 1.797]} scale={[1.169, 0.581, 1]} />
        <mesh name="Cube089" geometry={nodes.Cube089.geometry} material={materials['carte mov']} position={[0.207, 0.946, 1.797]} scale={[1.169, 0.698, 1]} />
        <mesh name="Cube090" geometry={nodes.Cube090.geometry} material={materials['carte rosie']} position={[0.207, 1.259, 1.797]} scale={[1.169, 0.581, 1]} />
        <mesh name="Cube091" geometry={nodes.Cube091.geometry} material={materials.comp} position={[-4.028, 2.114, 1.566]} scale={[1, 1, 0.774]} />
        <mesh name="Cube092" geometry={nodes.Cube092.geometry} material={materials.comp} position={[-5.276, 2.182, 1.948]} scale={[0.048, 0.498, 0.094]} />
        <mesh name="Cube093" geometry={nodes.Cube093.geometry} material={materials.comp} position={[-5.276, 2.182, 1.671]} scale={[0.048, 0.498, 0.094]} />
        <mesh name="Cube094" geometry={nodes.Cube094.geometry} material={materials.comp} position={[-5.276, 2.182, 1.47]} scale={[0.048, 0.498, 0.094]} />
        <mesh name="Cube095" geometry={nodes.Cube095.geometry} material={materials.comp} position={[-5.276, 2.182, 1.267]} scale={[0.048, 0.498, 0.094]} />
        <mesh name="Cube096" geometry={nodes.Cube096.geometry} material={materials['carte mov']} position={[-0.095, 0.003, -3.092]} scale={[1, 0.603, 1]} />
        <mesh name="Cube097" geometry={nodes.Cube097.geometry} material={materials['Material.003']} position={[-0.095, 0.003, -3.739]} scale={[1, 0.603, 1]} />
        <mesh name="Cube098" geometry={nodes.Cube098.geometry} material={materials['Material.004']} position={[-0.095, 0.003, -4.393]} scale={[1, 0.603, 1]} />
        <mesh name="Cube099" geometry={nodes.Cube099.geometry} material={materials['carte rosie']} position={[-0.095, 0.003, -5.097]} scale={[1, 0.603, 1]} />
        <group name="Plane009" position={[3.774, 0.568, -3.695]} rotation={[Math.PI / 2, 0, 0]} scale={[0.288, 0.051, 0.242]}>
          <mesh name="Plane009_1" geometry={nodes.Plane009_1.geometry} material={materials.raft} />
          <mesh name="Plane009_2" geometry={nodes.Plane009_2.geometry} material={materials['vazoncik mov']} />
          <mesh name="Plane009_3" geometry={nodes.Plane009_3.geometry} material={materials['carte marine']} />
        </group>
        <group name="Cube103" position={[-4.096, 1.465, -5.038]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.136, 0.442, 0.732]}>
          <mesh name="Cube097_1" geometry={nodes.Cube097_1.geometry} material={materials['Material.001']} />
          <mesh name="Cube097_2" geometry={nodes.Cube097_2.geometry} material={materials['Material.004']} />
          <mesh name="Cube097_3" geometry={nodes.Cube097_3.geometry} material={materials['Material.006']} />
        </group>
        <mesh name="Cube109" geometry={nodes.Cube109.geometry} material={materials['Material.001']} position={[-1.231, 5.276, 1.458]} rotation={[-1.008, -0.013, -0.011]} scale={[-0.087, -0.342, -0.087]} />
        <mesh name="Cylinder005" geometry={nodes.Cylinder005.geometry} material={materials['Material.002']} position={[-1.267, 4.566, 1.764]} scale={0.639} />
        <mesh name="Cube118" geometry={nodes.Cube118.geometry} material={materials['Material.003']} position={[2.845, 4.724, -1.49]} rotation={[2.01, -0.676, -1.023]} scale={[-0.133, -1.086, -0.133]} />
        <mesh name="Cylinder006" geometry={nodes.Cylinder006.geometry} material={materials['vazoncik mov']} position={[3.558, 3.753, -1.174]} scale={0.802} />
        <mesh name="Plane012" geometry={nodes.Plane012.geometry} material={materials.teava} position={[-4.961, 1.486, 3.543]} />
        <mesh name="Plane013" geometry={nodes.Plane013.geometry} material={materials['Material.011']} position={[0.952, 5.968, 3.084]} rotation={[Math.PI / 2, 0, 0]} scale={[0.286, 0.054, 0.376]} />
        <mesh name="Plane014" geometry={nodes.Plane014.geometry} material={materials['carte mov']} position={[0.383, 5.117, 3.084]} rotation={[Math.PI / 2, 0, 0]} scale={[0.286, 0.054, 0.376]} />
        <mesh name="Cube050" geometry={nodes.Cube050.geometry} material={materials['carte mov']} position={[3.935, 6.315, 1.988]} scale={[0.308, 0.09, 0.308]} />
        <mesh name="Cube048" geometry={nodes.Cube048.geometry} material={materials['carte mov']} position={[3.935, 5.945, 1.988]} scale={[0.308, 0.09, 0.308]} />
        <mesh name="Cube047" geometry={nodes.Cube047.geometry} material={materials['Material.004']} position={[3.935, 5.763, 1.988]} scale={[0.308, 0.09, 0.308]} />
      </group>
    </group>
  )
}

useGLTF.preload('./models/room.glb')
