/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 public/models/snake.gltf
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Snake(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('./models/snake.gltf')
  const { actions,names } = useAnimations(animations, group)
  console.log(names)

  useEffect(()=>{
    actions[names[0]].reset().fadeIn(0.5).play()
  },[])
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="BezierCircle" position={[0, 0, 0]} scale={2} />
        <group name="Cube001" position={[0, 0, 0]}>
          <mesh name="Cube001_1" geometry={nodes.Cube001_1.geometry} material={materials['Material.002']} />
          <mesh name="Cube001_2" geometry={nodes.Cube001_2.geometry} material={materials['Material.001']} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('./models/snake.gltf')
