/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 public/models/dbloop.glb
*/

import React, { useRef, useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('./models/dbloop.glb')
  const { actions,names } = useAnimations(animations, group)
  
  useEffect(()=>{
    actions[names[0]].reset().fadeIn(0.5).play()
  },[])
  
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh name="Circle" geometry={nodes.Circle.geometry} material={materials['Material.001']} />
        <mesh name="Circle001" geometry={nodes.Circle001.geometry} material={materials['Material.002']} position={[0, 0.43, 0]} />
        <mesh name="Circle002" geometry={nodes.Circle002.geometry} material={materials['Material.003']} position={[0, 0.86, 0]} />
        <mesh name="Circle003" geometry={nodes.Circle003.geometry} material={materials['Material.004']} position={[0, 1.49, 0]} />
      </group>
    </group>
  )
}

useGLTF.preload('./models/dbloop.glb')
