/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 public/models/dice2.glb
*/

import React, { useRef, useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('./models/dice2.glb')
  const { actions,names } = useAnimations(animations, group)
  
  useEffect(()=>{
    actions[names[0]].reset().fadeIn(0.5).play()
  },[])
  
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Cube" position={[0, 3.967, -3.419]} rotation={[0.561, -0.269, -0.401]}>
          <mesh name="Mesh" geometry={nodes.Mesh.geometry} material={materials.Dice} />
          <mesh name="Mesh_1" geometry={nodes.Mesh_1.geometry} material={materials.Hole} />
        </group>
        <group name="Cube001" position={[0, 1.71, 0]} rotation={[3.063, -0.334, 1.335]}>
          <mesh name="Mesh_2" geometry={nodes.Mesh_2.geometry} material={materials['Dice.004']} />
          <mesh name="Mesh_3" geometry={nodes.Mesh_3.geometry} material={materials['Hole.004']} />
        </group>
        <group name="Cube002" position={[0.367, 4.913, 2.708]} rotation={[-0.283, -0.357, -2.265]}>
          <mesh name="Mesh_4" geometry={nodes.Mesh_4.geometry} material={materials['Dice.005']} />
          <mesh name="Mesh_5" geometry={nodes.Mesh_5.geometry} material={materials['Hole.005']} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('./models/dice2.glb')
