/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 public/models/pyth.glb
*/

import React, { useRef, useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('./models/pyth.glb')
  const { actions,names } = useAnimations(animations, group)

  useEffect(()=>{
    actions[names[0]].reset().fadeIn(0.5).play()
  },[])


  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Plane" position={[0.951, 1.765, -0.502]} rotation={[Math.PI / 2, 0, 0]} scale={0.809}>
          <mesh name="Plane_1" geometry={nodes.Plane_1.geometry} material={materials['Material.001']} />
          <mesh name="Plane_2" geometry={nodes.Plane_2.geometry} material={materials['Material.003']} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('./models/pyth.glb')
