/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 public/models/w2.glb
*/

import React, { useRef, useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('./models/w2.glb')
  const { actions, names } = useAnimations(animations, group)
  
  useEffect(()=>{
    actions[names[0]].reset().fadeIn(0.5).play()
  },[])
  
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Circle" />
        <mesh name="Circle001" geometry={nodes.Circle001.geometry} material={materials['Material.001']} />
        <mesh name="Circle002" geometry={nodes.Circle002.geometry} material={materials['Material.001']} />
        <mesh name="Circle003" geometry={nodes.Circle003.geometry} material={materials['Material.001']} />
        <mesh name="Circle004" geometry={nodes.Circle004.geometry} material={materials['Material.001']} />
        <mesh name="Circle005" geometry={nodes.Circle005.geometry} material={materials['Material.001']} />
        <mesh name="Circle006" geometry={nodes.Circle006.geometry} material={materials['Material.001']} />
        <mesh name="Circle007" geometry={nodes.Circle007.geometry} material={materials['Material.001']} />
        <mesh name="Icosphere" geometry={nodes.Icosphere.geometry} material={materials['Material.001']} position={[0, 1, 0]} scale={0.188} />
      </group>
    </group>
  )
}

useGLTF.preload('./models/w2.glb')
